-- ============================================================
-- SAFEPIT APP — MySQL Database Schema
-- Matches ER Diagram: user, sos_alert, incident_report,
--                     checklist, notification, reports
-- ============================================================

CREATE DATABASE IF NOT EXISTS safepit_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE safepit_db;

-- ============================================================
-- TABLE 1: user
-- Roles: worker | supervisor | admin
-- ============================================================
CREATE TABLE IF NOT EXISTS user (
  user_id       INT AUTO_INCREMENT PRIMARY KEY,
  name          VARCHAR(100)  NOT NULL,
  email         VARCHAR(100)  UNIQUE NOT NULL,
  password      VARCHAR(255)  NOT NULL,           -- bcrypt hash
  role          ENUM('worker','supervisor','admin') NOT NULL,
  phone_no      VARCHAR(20),
  preferred_lang ENUM('English','Hindi','Tamil','Telugu','Odia') DEFAULT 'English',
  job_role      VARCHAR(50) DEFAULT 'General',    -- e.g., Electrician, Driller, etc.
  supervisor_id INT,                              -- FK → user(user_id) for workers
  is_active     BOOLEAN DEFAULT TRUE,
  created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (supervisor_id) REFERENCES user(user_id) ON DELETE SET NULL
);

-- ============================================================
-- TABLE 2: incident_report  (from ER: user 1→N incident_report)
-- ============================================================
CREATE TABLE IF NOT EXISTS incident_report (
  report_id     INT AUTO_INCREMENT PRIMARY KEY,
  user_id       INT NOT NULL,
  description   TEXT NOT NULL,
  location      VARCHAR(200),
  severity      ENUM('LOW','MEDIUM','HIGH','CRITICAL') NOT NULL,
  status        ENUM('OPEN','ACKNOWLEDGED','RESOLVED') DEFAULT 'OPEN',
  created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES user(user_id)
);

-- ============================================================
-- TABLE 3: checklist  (from ER: checklist_id, report_id,
--           task_description, task_status, completed_by)
-- Admin uploads tasks; workers complete them
-- ============================================================
CREATE TABLE IF NOT EXISTS checklist (
  checklist_id      INT AUTO_INCREMENT PRIMARY KEY,
  report_id         INT,                          -- links to incident_report if needed
  task_description  TEXT NOT NULL,
  task_status       ENUM('PENDING','COMPLETED') DEFAULT 'PENDING',
  completed_by      INT,                          -- user_id of worker who completed
  role_target VARCHAR(50) DEFAULT 'all',
  shift_target      ENUM('Morning','Afternoon','Night','All') DEFAULT 'All',
  lang              ENUM('English','Hindi','Tamil','Telugu','Odia') DEFAULT 'English',
  task_group_id     BIGINT DEFAULT NULL,          -- groups translated versions of same task
  created_by        INT NOT NULL,                 -- admin user_id
  completion_date   DATE,
  created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (report_id)    REFERENCES incident_report(report_id) ON DELETE SET NULL,
  FOREIGN KEY (completed_by) REFERENCES user(user_id) ON DELETE SET NULL,
  FOREIGN KEY (created_by)   REFERENCES user(user_id)
);

-- ============================================================
-- TABLE 4: sos_alert  (from ER: sos_id, user_id, report_id,
--           alert_time, status)
-- Worker triggers → supervisor notified
-- ============================================================
CREATE TABLE IF NOT EXISTS sos_alert (
  sos_id        INT AUTO_INCREMENT PRIMARY KEY,
  user_id       INT NOT NULL,                     -- worker who triggered
  report_id     INT,                              -- optional linked report
  alert_time    DATETIME DEFAULT CURRENT_TIMESTAMP,
  status        ENUM('ACTIVE','ACKNOWLEDGED','RESOLVED') DEFAULT 'ACTIVE',
  location      VARCHAR(200),
  acknowledged_by INT,
  resolved_at   DATETIME,
  FOREIGN KEY (user_id)          REFERENCES user(user_id),
  FOREIGN KEY (report_id)        REFERENCES incident_report(report_id) ON DELETE SET NULL,
  FOREIGN KEY (acknowledged_by)  REFERENCES user(user_id) ON DELETE SET NULL
);

-- ============================================================
-- TABLE 5: notification  (from ER: notification_id, user_id,
--           report_id, message)
-- Generated by: sos_alert (1→1) and incident_report (1→1)
-- ============================================================
CREATE TABLE IF NOT EXISTS notification (
  notification_id INT AUTO_INCREMENT PRIMARY KEY,
  user_id         INT NOT NULL,                   -- who receives notification
  report_id       INT,
  message         TEXT NOT NULL,
  is_read         BOOLEAN DEFAULT FALSE,
  created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id)   REFERENCES user(user_id),
  FOREIGN KEY (report_id) REFERENCES incident_report(report_id) ON DELETE SET NULL
);

-- ============================================================
-- TABLE 6: reports  (from ER: report_id, user 1→N)
-- Admin-uploaded content: tips, statements, guidelines
-- ============================================================
CREATE TABLE IF NOT EXISTS reports (
  report_id     INT AUTO_INCREMENT PRIMARY KEY,
  user_id       INT NOT NULL,                     -- admin who uploaded
  type          ENUM('safety_tip','positive_statement','dgms_guideline') NOT NULL,
  title         VARCHAR(200),
  content       TEXT NOT NULL,
  lang          ENUM('English','Hindi','Tamil','Telugu','Odia') DEFAULT 'English',
  is_active     BOOLEAN DEFAULT TRUE,
  created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES user(user_id)
);

-- ============================================================
-- SEED DATA
-- ============================================================

-- Admin
INSERT INTO user (name, email, password, role, preferred_lang) VALUES
('System Admin', 'xyz.admin@gmail.com', '$2b$10$placeholder_admin', 'admin', 'English');

-- Supervisor
INSERT INTO user (name, email, password, role, phone_no, preferred_lang) VALUES
('Suresh Sharma', 'suresh@safepit.com', '$2b$10$placeholder_sup', 'supervisor', '9876543210', 'English');

-- Worker
INSERT INTO user (name, email, password, role, phone_no, preferred_lang, supervisor_id, job_role) VALUES
('Rajesh Kumar', 'rajesh@safepit.com', '$2b$10$placeholder_worker', 'technician', '9123456789', 'Tamil', 2, 'Driller');

-- Default checklist tasks (uploaded by admin)
INSERT INTO checklist (task_description, role_target, shift_target, created_by, lang, task_group_id) VALUES
('Inspect PPE before starting — helmet, boots, gloves, vest', 'all', 'All', 1, 'English', 1),
('शुरू करने से पहले पीपीई जांचें — हेलमेट, बूट, दस्ताने, वेस्ट', 'all', 'All', 1, 'Hindi', 1),
('தொடங்குவதற்கு முன் PPE பரிசோதனை செய்க — ஹெல்மெட், பூட்ஸ், கைவார்த்தைகள், வெஸ்ட்', 'all', 'All', 1, 'Tamil', 1),
('ప్రారంబించడానికి ముందు PPE‌ను పరిశీలించండి — హెల్మెట్, బూట్లు, గ్లౌవ్స్, వెస్ట్', 'all', 'All', 1, 'Telugu', 1),
('ଆରମ୍ଭ କରିବା ପୂର୍ବରୁ PPE ଯାଞ୍ଚ କରନ୍ତୁ — ହେଲମେଟ୍, ବୁଟ୍, ହାତମୋଜା, ଭେସ୍ଟ', 'all', 'All', 1, 'Odia', 1),
('Check machine oil and fuel levels before operation', 'all', 'All', 1, 'English', 2),
('ऑपरेशन से पहले मशीन का तेल और ईंधन स्तर जांचें', 'all', 'All', 1, 'Hindi', 2),
('செயல்பாட்டிற்கு முன் இயந்திர எண்ணெய் மற்றும் எரிபொருள் நிலைகளை பரிசோதிக்கவும்', 'all', 'All', 1, 'Tamil', 2),
('ఆపరేషన్‌కి ముందు యంత్ర నూనె మరియు ఇంధన స్థాయిలను తనిఖీ చేయండి', 'all', 'All', 1, 'Telugu', 2),
('ଓପରେସନ୍ ପୂର୍ବରୁ ଯନ୍ତ୍ର ତେଲ ଓ ଇନ୍ଧନ ସ୍ତର ଯାଞ୍ଚ କରନ୍ତୁ', 'all', 'All', 1, 'Odia', 2),
('Test brakes and steering — verify all controls function', 'all', 'All', 1, 'English', 3),
('ब्रेक और स्टीयरिंग की जांच करें — सभी नियंत्रण काम कर रहे हैं', 'all', 'All', 1, 'Hindi', 3),
('பிரேக்குகள் மற்றும் ஸ்டீயரிங் ஐ சோதிக்கவும் — அனைத்து கட்டுப்பாடுகளும் செயல்படுகின்றன என்பதை உறுதிசெய்க', 'all', 'All', 1, 'Tamil', 3),
('బ్రేక్స్ మరియు స్టీరింగ్‌ను పరీక్షించండి — అన్ని నియంత్రణలు పనిచేస్తున్నాయని నిర్ధారించండి', 'all', 'All', 1, 'Telugu', 3),
('ବ୍ରେକ୍ ଓ ଷ୍ଟିୟରିଂ ପରୀକ୍ଷା କରନ୍ତୁ — ସମସ୍ତ ନିୟନ୍ତ୍ରଣ କାମ କରୁଛି କି ନାହିଁ ଯାଞ୍ଚ କରନ୍ତୁ', 'all', 'All', 1, 'Odia', 3),
('Verify safety guards are in place on all moving parts', 'all', 'All', 1, 'English', 4),
('सभी चलती भागों पर सुरक्षा गार्ड लगे हैं यह जांचें', 'all', 'All', 1, 'Hindi', 4),
('அனைத்து நகரும் பகுதிகளிலும் பாதுகாப்பு கேர்கள் உள்ளதா என்று உறுதிசெய்க', 'all', 'All', 1, 'Tamil', 4),
('అన్ని కదలిక భాగాలలో సేఫ్టీ గార్డ్లు ఉన్నాయా అని ధృవీకరించండి', 'all', 'All', 1, 'Telugu', 4),
('ସମସ୍ତ ଚଳିତ ଅଂଶରେ ସୁରକ୍ଷା ଗାର୍ଡ ଥାଏ କି ନାହିଁ ଯାଞ୍ଚ କରନ୍ତୁ', 'all', 'All', 1, 'Odia', 4),
('Check for leaks or loose wires — look for visible damage', 'all', 'All', 1, 'English', 5),
('लीक्स या ढीले तारों की जांच करें — दृश्य क्षति देखें', 'all', 'All', 1, 'Hindi', 5),
('சிதைவுகள் அல்லது தளர்ந்த கம்பிகளை கண்டறியவும் — காட்சிப் பாழை பாருங்கள்', 'all', 'All', 1, 'Tamil', 5),
('చీరికలు లేదా సడలిన వైర్లను తనిఖీ చేయండి — కనిపించే ధ్వంసాన్ని చూడండి', 'all', 'All', 1, 'Telugu', 5),
('ଛିଦ୍ର ଓ ଢିଲା ତାରଗୁଡ଼ିକୁ ଯାଞ୍ଚ କରନ୍ତୁ — ଦୃଶ୍ୟମାନ ନଷ୍ଟ ଖୋଜନ୍ତୁ', 'all', 'All', 1, 'Odia', 5),
('Drill-specific: Check drill bit integrity and alignment', 'Driller', 'All', 1, 'English', 6),
('ड्रिल-विशिष्ट: ड्रिल बिट की अखंडता और संरेखण जांचें', 'Driller', 'All', 1, 'Hindi', 6),
('திரில்-சிறப்பு: திரில் பிடியின் சுற்றுப்புறமும் சீர்கேடானதா என்பதைப் பழுதாய்வு செய்க', 'Driller', 'All', 1, 'Tamil', 6),
('డ్రిల్-స్పెసిఫిక్: డ్రిల్ బిట్ ఖచ్చితత్వాన్ని మరియు సన్నద్ధతను తనిఖీ చేయండి', 'Driller', 'All', 1, 'Telugu', 6),
('ଡ୍ରିଲ୍-ବିଶେଷ: ଡ୍ରିଲ୍ ବିଟ୍ ଏବଂ ସମନ୍ୱୟ ଯାଞ୍ଚ କରନ୍ତୁ', 'Driller', 'All', 1, 'Odia', 6),
('Blaster-specific: Verify explosive storage and handling protocols', 'Blaster', 'All', 1, 'English', 7),
('ब्लास्टर-विशिष्ट: विस्फोटक भंडारण और हैंडलिंग प्रोटोकॉल जांचें', 'Blaster', 'All', 1, 'Hindi', 7),
('பிளாஸ்டர்-சிறப்பு: வெடிநுணுக்கக் கையரிப்பு மற்றும் கையாளுதல் நெறிமுறைகளை உறுதிசெய்க', 'Blaster', 'All', 1, 'Tamil', 7),
('బ్లాస్టర్-స్పెసిఫిక్: పేలిక సర్వే మరియు నిర్వహణ ప్రోటోకాల్‌లను ధృవీకరించండి', 'Blaster', 'All', 1, 'Telugu', 7),
('ବ୍ଲାଷ୍ଟର୍-ବିଶେଷ: ବିସ୍ଫୋଟକ ଗୋଡ଼ାଉଜ୍ ଓ ହ୍ୟାଣ୍ଡଲିଙ୍ଗ ପ୍ରଟୋକଲ ଯାଞ୍ଚ କରନ୍ତୁ', 'Blaster', 'All', 1, 'Odia', 7);

-- Default safety tips (multilingual)
INSERT INTO reports (user_id, type, title, content, lang) VALUES
(1, 'safety_tip', 'Evacuation Routes', 'Know your emergency evacuation routes.', 'English'),
(1, 'safety_tip', 'ప్రారంభించే', 'పని ప్రారంభించే ముందు PPEను ధరించండి.', 'Telugu'),
(1, 'safety_tip', 'ଯାଞ୍ଚ', 'କାମ ଆରମ୍ଭ କରିବା ପୂର୍ବରୁ PPE ପିନ୍ଧନ୍ତୁ।', 'Odia'),

(1, 'positive_statement', 'Safety First', 'Safety first, work second. Every life matters!', 'English'),
(1, 'positive_statement', 'భద్రత మొదట', 'భద్రత మొదట, పని తరువాత. ప్రతి ప్రాణం ముఖ్యం!', 'Telugu'),
(1, 'positive_statement', 'ସୁରକ୍ଷା ପ୍ରଥମେ', 'ସୁରକ୍ଷା ପ୍ରଥମେ, କାମ ପରେ। ପ୍ରତ୍ୟେକ ଜୀବନ ମୂଲ୍ୟବାନ।', 'Odia'),

(1, 'dgms_guideline', 'Mines Act 1952', 'This app follows DGMS guidelines under the Mines Act, 1952. Always comply with safety protocols.', 'English'),
(1, 'dgms_guideline', 'Mines Act 1952', 'यह ऐप खनन अधिनियम, 1952 के तहत DGMS दिशानिर्देशों का पालन करता है। हमेशा सुरक्षा प्रोटोकॉल का पालन करें।', 'Hindi'),
(1, 'dgms_guideline', 'Mines Act 1952', 'இந்த செயலி மைன்ஸ் சட்டம் 1952 மற்றும் DGMS வழிகாட்டுதல்களை பின்பற்றி செயல்படுகிறது. எப்போதும் பாதுகாப்பு விதிகளுக்கு உடன்பாடு கிடைக்க வேண்டும்.', 'Tamil'),
(1, 'dgms_guideline', 'Mines Act 1952', 'ఈ యాప్ మైన్స్ యాక్ట్ 1952 కింద DGMS మార్గదర్శకాలను అనుసరిస్తుంది. సురక్షిత నియమాలను ఎప్పుడూ పాటించండి.', 'Telugu'),
(1, 'dgms_guideline', 'Mines Act 1952', 'ଏହି ଆପ୍ ମାଇନ୍ସ ଏକ୍ଟ 1952 ଅନ୍ତର୍ଗତ DGMS ନିର୍ଦ୍ଦେଶାବଳୀକୁ ଅନୁସରଣ କରିଥାଏ। ସୁରକ୍ଷା ନିୟମ ମାନିବାକୁ ସବୁବେଳେ ପ୍ରଥମତା ଦିଅନ୍ତୁ।', 'Odia');
